### ISSUE TITLE
`Get MD5 For File.vi` should not have to be in the Always Included section of the Scripting API build spec.

### ISSUE THREAD

**Issue by douglasnorman** [ni/niveristand-ballard-arinc429-custom-device#112]
**Describe the bug**
A local build of **Scripting API** build spec works fine. but on a build machine `Get MD5 For File.vi` has to be in the **Always Included** section of the Scripting API build spec or it doesn't get included.

**To Reproduce**
1. Build the **Scripting API** build spec on a build machine without `Get MD5 For File.vi` in the **Always Included** section of  the build spec.

**Expected behavior**
Build the **Scripting API** build spec on a build machine without `Get MD5 For File.vi` in the **Always Included** section, and that VI should be included in the output.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by dbendele** [comment]
reference commit https://github.com/ni/niveristand-ballard-arinc429-custom-device/pull/182/commits/83e881762bc97d165306eb9fb4011e0b6df30f2c
