### ISSUE TITLE
Braodcast Message.VI was not found when source code downloaded

### ISSUE THREAD

**Issue by fco333** [ni/niveristand-ballard-arinc429-custom-device#207]
**Is your feature request related to a problem? Please describe.**
The missing file is causing not able to open custom device free of broken arrows and be able to be compile

**Describe the solution you'd like**
Please add the  Braodcast Message.VI

**Describe alternatives you've considered**
If there is a workaround let us know

**Additional context**
![missing VI](https://user-images.githubusercontent.com/96260247/155229601-917fedff-1847-4d63-9249-f1ddf537920c.png)

**Comment by Karl-G1** [comment]
@fco333 
To build the custom device from source, you need the dependencies listed in the [readme](https://github.com/ni/niveristand-ballard-arinc429-custom-device#developing-or-building-from-source) (which were updated recently). The particular issue you are seeing is probably that the [Custom Device Message Library](https://github.com/ni/niveristand-custom-device-message-library/releases) package is not installed. It contains the classes used by the logging code in the custom device.

That said, I would recommend installing the custom device from the NI Packages hosted on the [release page](https://github.com/ni/niveristand-ballard-arinc429-custom-device/releases) of this repository. You should only need to build the custom device yourself if you are modifying it.
